title = "gitleaks config for enchant_cli"

[extend]
useDefault = true

[allowlist]
description = "Allowlisted files"
paths = [
    '''\.lock$''',
    '''\.log$''',
    '''\.pyc$''',
    '''__pycache__''',
    '''\.git/''',
    '''\.venv/''',
    '''node_modules/''',
    '''test_secret\.py''',  # Temporarily allow our test file
]

# Additional custom rules can be added here if needed
