# Markdown Lint Configuration for Super-Linter

# Default state for all rules
default: true

# Path to files to ignore
excludes: []

# MD003/heading-style - Heading style
MD003:
  style: atx

# MD004/ul-style - Unordered list style
MD004:
  style: dash

# MD007/ul-indent - Unordered list indentation
MD007:
  indent: 2

# MD013/line-length - Line length
MD013:
  line_length: 120
  heading_line_length: 120
  code_blocks: false
  tables: false

# MD024/no-duplicate-heading - Multiple headings with the same content
MD024:
  siblings_only: true

# MD026/no-trailing-punctuation - Trailing punctuation in heading
MD026:
  punctuation: ".,;:!。，；：！"

# MD029/ol-prefix - Ordered list item prefix
MD029:
  style: ordered

# MD033/no-inline-html - Inline HTML
MD033:
  allowed_elements: []

# MD035/hr-style - Horizontal rule style
MD035:
  style: "---"

# MD036/no-emphasis-as-heading - Emphasis used instead of a heading
MD036: false

# MD041/first-line-h1 - First line in file should be a top level heading
MD041: false

# MD046/code-block-style - Code block style
MD046:
  style: fenced
