#!/usr/bin/env python3
# -*- coding: utf-8 -*-

name: Docker Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
    - 'Dockerfile'
    - 'docker-compose.yml'
    - '.dockerignore'
    - 'src/**'
    - 'tests/**'
    - 'pyproject.toml'
    - 'uv.lock'

permissions:
  contents: read

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build test image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: enchant-test:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run tests in Docker
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      run: |
        docker-compose up --abort-on-container-exit test

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report
        path: |
          htmlcov/
          test-results/

  docker-build-prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build production image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.prod
        push: false
        tags: enchant-book-manager:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test production image
      run: |-
        docker run --rm enchant-book-manager:latest --help
