name: Update Documentation

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'docs/**'
      - 'README.md'
      - 'pyproject.toml'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv venv
          uv sync --all-extras
          uv add --dev sphinx sphinx-rtd-theme myst-parser

      - name: Generate API documentation
        run: |
          # Create docs directory if it doesn't exist
          mkdir -p docs
          # Generate Sphinx configuration if needed
          if [ ! -f docs/conf.py ]; then
            cd docs
            uv run sphinx-quickstart -q -p "EnChANT Book Manager" -a "Emasoft" \
              -v "0.1.0" --ext-autodoc --ext-viewcode --makefile
            cd ..
          fi
          # Build documentation
          uv run sphinx-build -b html docs docs/_build/html

      - name: Update README badges
        run: |
          # Update version badge
          VERSION=$(uv run python -c "import enchant_book_manager; print(enchant_book_manager.__version__)")
          sed -i "s/python-[0-9.]\+-blue/python-$VERSION-blue/g" README.md || true

      - name: Upload Pages artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages

      - name: Update PyPI description
        if: github.event_name == 'push' && contains(github.event.head_commit.message, '[release]')
        run: |
          echo "PyPI description would be updated here after release"
