name: Pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python environment
        run: |
          uv python install 3.12
          uv sync --all-extras

      - name: Install actionlint
        run: |
          # Install actionlint for GitHub Actions linting
          mkdir -p ~/.local/bin
          curl -L "https://github.com/rhysd/actionlint/releases/latest/download/actionlint_$(uname -s | tr '[:upper:]' '[:lower:]')_amd64.tar.gz" | tar xz -C ~/.local/bin
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Run pre-commit
        run: uv run pre-commit run --all-files --show-diff-on-failure --color=always
