name: Pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python environment
        run: |
          uv python install 3.12
          uv sync --all-extras

      - name: Install actionlint
        run: |
          # Install actionlint for GitHub Actions linting
          mkdir -p ~/.local/bin
          VERSION="1.7.7"
          ARCH="amd64"
          OS="linux"
          URL="https://github.com/rhysd/actionlint/releases/download/v${VERSION}/actionlint_${VERSION}_${OS}_${ARCH}.tar.gz"
          curl -L "${URL}" | tar xz -C ~/.local/bin actionlint
          chmod +x ~/.local/bin/actionlint
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Install yamlfmt
        run: |
          # Install Go if not available
          if ! command -v go &> /dev/null; then
            wget -q https://go.dev/dl/go1.21.0.linux-amd64.tar.gz
            sudo tar -C /usr/local -xzf go1.21.0.linux-amd64.tar.gz
            export PATH=$PATH:/usr/local/go/bin
          fi
          # Install yamlfmt
          go install github.com/google/yamlfmt/cmd/yamlfmt@latest
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

      - name: Run pre-commit
        run: uv run pre-commit run --all-files --show-diff-on-failure --color=always
