name: PR Fix

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
  pr-fix:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Install dependencies
      run: |
        uv venv
        uv sync --all-extras
        go install github.com/google/yamlfmt/cmd/yamlfmt@latest

    - name: Run pre-commit hooks
      run: |
        uv run pre-commit run --all-files || true

    - name: Check for changes
      id: changes
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "changes=true" >> "$GITHUB_OUTPUT"
        else
          echo "changes=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Commit and push changes
      if: steps.changes.outputs.changes == 'true'
      run: |-
        git config --local user.email "713559+Emasoft@users.noreply.github.com"
        git config --local user.name "Emasoft"
        git add -A
        git commit -m "fix: auto-fix linting and formatting issues in PR"
        git push
